package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.leeboonstra.dialogflow_grpc.DialogflowGrpcPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin dialogflow_grpc, com.leeboonstra.dialogflow_grpc.DialogflowGrpcPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new vn.casperpas.sound_stream.SoundStreamPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin sound_stream, vn.casperpas.sound_stream.SoundStreamPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin url_launcher, io.flutter.plugins.urllauncher.UrlLauncherPlugin", e);
    }
  }
}
